name: Build & Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3     
    - uses: bahmutov/npm-install@v1
    - name: Build
      run: npm run build
    - name: Deploy
      uses: up9cloud/action-rsync@master
      env:
        HOST: w01d1f1b.kasserver.com
        USER: ssh-w01008fe
        KEY: ${{secrets.SSH_PRIVATE_KEY}}
        ARGS: -ar --delete
        SOURCE: out/
        TARGET: /www/htdocs/w01d1f1b/meshup.mhoff.net
